export const GO_TO_PROFILE = 'GO_TO_PROFILE'
export const BACK_TO_LIST = 'BACK_TO_LIST'
export const INIT_LIST_AND_PROFILE = 'INIT_LIST_AND_PROFILE'

export const QUERY_LIST = 'QUERY_LIST'

export const CHANGE_ROUTER = 'CHANGE_ROUTER'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOAD_LOGIN_USER = 'LOAD_LOGIN_USER'
export const UPDATE_LOGIN_USER = 'UPDATE_LOGIN_USER'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RELOAD_AUTH = 'RELOAD_AUTH'

export const LOAD_ADMIN_LIST = 'LOAD_ADMIN_LIST'
export const VIEW_ADMIN = 'VIEW_ADMIN'
export const ADD_ADMIN = 'ADD_ADMIN'
export const UPDATE_ADMIN = 'UPDATE_ADMIN'
export const DELETE_ADMIN = 'DELETE_ADMIN'

export const LOAD_USER_LIST = 'LOAD_USER_LIST'
export const VIEW_USER = 'VIEW_USER'
export const ADD_USER = 'ADD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const CHECK_USER = 'CHECK_USER'
export const UNCHECK_USER = 'UNCHECK_USER'
export const BATCH_CHECK_USER = 'BATCH_CHECK_USER'
export const BATCH_UNCHECK_USER = 'BATCH_UNCHECK_USER'
export const RECOMMEND_USER = 'RECOMMEND_USER'
export const UNRECOMMEND_USER = 'UNRECOMMEND_USER'

export const LOAD_ADMIN_ROLE_LIST = 'LOAD_ADMIN_ROLE_LIST'
export const VIEW_ROLE = 'VIEW_ROLE'
export const ADD_ROLE = 'ADD_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'
export const UPDATE_ROLE_PERMS = 'UPDATE_ROLE_PERMS'

export const VIEW_PPT = 'VIEW_PPT'
export const LOAD_PPT = 'LOAD_PPT'
export const ADD_PPT = 'ADD_PPT'
export const UPDATE_PPT = 'UPDATE_PPT'
export const DELETE_PPT = 'DELETE_PPT'

export const LOAD_BANNER_LIST = 'LOAD_BANNER_LIST'
export const VIEW_BANNER = 'VIEW_BANNER'
export const UPDATE_BANNER = 'UPDATE_BANNER'

export const VIEW_TAG = 'VIEW_TAG'
export const LOAD_TAGS = 'LOAD_TAGS'
export const ADD_TAG = 'ADD_TAG'
export const UPDATE_TAG = 'UPDATE_TAG'
export const DELETE_TAG = 'DELETE_TAG'

export const VIEW_MESSAGE = 'VIEW_MESSAGE'
export const LOAD_MESSAGE = 'LOAD_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'

export const LOAD_MOVIE_LIST = 'LOAD_MOVIE_LIST'
export const VIEW_MOVIE = 'VIEW_MOVIE'
export const LOAD_PHOTO_LIST = 'LOAD_PHOTO_LIST'
export const VIEW_PHOTO = 'VIEW_PHOTO'
export const LOAD_VIDEO_LIST = 'LOAD_VIDEO_LIST'
export const VIEW_VIDEO = 'VIEW_VIDEO'

